site_name: CoinGecko API Service
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("backend")
          options:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - API Reference:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
    - Models: api/models.md
  - Development:
    - Setup: development/setup.md
    - Contributing: development/contributing.md